{% set name = "pyfftlog" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00811ee6be5b59c7da4fce31292ab308a992d6e4455fbe33a05112a3e66211c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
    - setuptools_scm
  run:
    - python >=3.10
    - numpy
    - scipy >=1.10

test:
  imports:
    - pyfftlog

about:
  home: https://github.com/emsig/pyfftlog
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: 'Logarithmic Fast Fourier Transform'
  description: |
    A pure python implementation of the logarithmic FFT code FFTLog
    as presented in Appendix B of Hamilton (2000) and published at
    jila.colorado.edu/~ajsh/FFTLog.
  doc_url: https://pyfftlog.readthedocs.io/
  dev_url: https://github.com/emsig/pyfftlog

extra:
  recipe-maintainers:
    - prisae
